### PR TITLE
added reviews list with little sample data, added tests

### PR DESCRIPTION
**Pull request by saraschaeffer**
- no styling yet
- added some sample reviews and rendered some properties of them
- created tests for those

### CODE REVIEW

**Comment by saraschaeffer** [comment]
@AdamPJohnson It looks like my CircleCI tests are failing because of some failing tests in your components. I did pull down from main when I started working on this, but maybe you made changes since then? Ping me on slack if you want to discuss further.

**Comment by saraschaeffer** [comment]
@finchzebra Hold off on reviewing until I can fix my failing tests

**Comment by saraschaeffer** [comment]
@finchzebra resolved the failing tests. You're now free to review

**Review by finchzebra — COMMENTED** [review]
Looks good to merge.

**Pull request merged**
