### PR TITLE
Css styling basic components

### PR DESCRIPTION
**Pull request by ykim9611**

### CODE REVIEW

**Comment by AdamPJohnson** [comment]
Have you fixed these conflicts?

**Comment by ykim9611** [comment]
@AdamPJohnson I will resolve the conflicts once you merge your pull requests.

**Comment by ykim9611** [comment]
@AdamPJohnson I have resolved the conflicts with the current master branch

**Comment by AdamPJohnson** [comment]
Can you fix this failing test? Dont wanna have everyones tests failing

**Comment by AdamPJohnson** [comment]
good good!

**Pull request merged**
