### PR TITLE
Little questions and answers

### PR DESCRIPTION
**Pull request by ykim9611**
If there are less than  5 questions, the 'more answered questions' button will not be present.
If there are less than 3 answers for a question, the 'more Answers' button will not be present.

### CODE REVIEW

**Comment by ykim9611** [comment]
@finchzebra @saraschaeffer This one too :)

**Comment by saraschaeffer** [comment]
I'll take this one too

**Review by saraschaeffer — APPROVED** [review]
I'd add a space between More and Answers on that button, but other than that, it looks good.

**Comment by ykim9611** [comment]
@saraschaeffer Thanks for the suggestion!

**Pull request merged**
